{"name": "Получение заказов неавторизованного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 401\n +  where 403 = <Response [403]>.status_code", "trace": "self = <Diplom_2.tests.test_get_user_orders.TestGetUserOrders object at 0x00000203BBC12350>\n\n    @allure.title('Получение заказов неавторизованного пользователя')\n    def test_get_orders_unauthorized(self):\n        response = self.api.get_user_orders('invalid_token')\n>       assert response.status_code == 401\nE       assert 403 == 401\nE        +  where 403 = <Response [403]>.status_code\n\ntests\\test_get_user_orders.py:30: AssertionError"}, "start": 1751988284592, "stop": 1751988284961, "uuid": "267bd967-06c0-44ba-b387-9550f199228c", "historyId": "92bf968573314a866ca27467231d26bc", "testCaseId": "92bf968573314a866ca27467231d26bc", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_orders_unauthorized", "labels": [{"name": "feature", "value": "Получение заказов пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-42BDC19"}, {"name": "thread", "value": "23912-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}